### ISSUE TITLE
fetchDataByPersonalId API call will be after application found

### ISSUE THREAD

**Issue by shivanim11** [Globalshala/Eval-Bridge-bugs#301]
**Describe the bug**
currently if we enter appid and that does not exist in DB then also there is personal id api call for that appid it should not be there it will check appid first if it found then we will call personal id api

**Screenshots**
![image](https://github.com/user-attachments/assets/4abe1b7e-74ae-4a5f-b5a2-f27b5dc19af5)

**Comment by shivanim11** [comment]
Fixed on dev

**Comment by Arunava-globalshala** [comment]
Not Fixed 

![Image](https://github.com/user-attachments/assets/a1a6eb41-83a8-4324-ba36-0e818db15baf)

![Image](https://github.com/user-attachments/assets/025af996-afed-4faa-9b40-ecd983d1f91c)

**Comment by Arunava-globalshala** [comment]
We don't need to call the transcript api also if we don't found the appID

![Image](https://github.com/user-attachments/assets/e97cdb6d-951c-47bd-9b24-2f7c9e4a7d95)

**Comment by shivanim11** [comment]
https://github.com/Globalshala/Eval-Bridge-bugs/issues/330
