### ISSUE TITLE
Create User issue

### ISSUE THREAD

**Issue by shivanim11** [Globalshala/Eval-Bridge-bugs#400]
**Describe the bug**
1. create user and click on save changes and see error

**Expected behavior**
it should create an user and should not throw error
**Screenshots**

![Image](https://github.com/user-attachments/assets/6aeb4b53-4d34-4899-bd6a-d9dde48175e0)

**Comment by bhaw18** [comment]
resolved

**Comment by Arunava-globalshala** [comment]
Not Fixed

![Image](https://github.com/user-attachments/assets/31d31e45-ff18-4d6d-aecd-25b9d86a365d)
